export const profileConstants = {
  PROFILE_POST_SUCCESS: "PROFILE_POST_SUCCESS",
  PROFILE_POST_FAILURE: "PROFILE_POST_FAILURE",

  EDIT_PROFILE_POST_SUCCESS: "EDIT_PROFILE_POST_SUCCESS",
  EDIT_PROFILE_POST_FAILURE: "EDIT_PROFILE_POST_FAILURE",

  PROFILE_RESET: "PROFILE_RESET",
};
