export const adminConstants = {
  AUTHENTICATION_FAILURE: "AUTHENTICATION_FAILURE",
  AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",

  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",

  LOGOUT_ACTION: "LOGOUT_ACTION",

  RESET_ERROR: "RESET_ERROR",
  
  RESET_LOGOUT: "RESET_LOGOUT",
};
